### ISSUE TITLE
Document "bootstrapping"

### ISSUE THREAD

**Issue by pgj** [pgj/freebsd-wifibox-image#2]
Extend the `wifibox-guest(5)` man page with information on how to install packages (for e.g. missing firmwares) when no Internet connection is available for the guest.  https://github.com/pgj/freebsd-wifibox/issues/6#issuecomment-1003378323 could serve a basis.

**Comment by suchipi** [comment]
It looks like `apk` isn't included in the image anymore, so the linked instructions don't work. It also seems that the image is a readonly squashfs image now, so the linked instructions wouldn't work even if `apk` was available. Is there a new way to hook into the image build process to add additional drivers/firmware?

**Comment by pgj** [comment]
Yes, you are right.  This repository is technically deprecated as this is not supported by the recent versions of Wifibox.  I should have closed this ticket and archived the repository a while ago.

To answer your question: if you want to hook up additional drivers or firmware, you should look into the `net/wifibox-alpine` port.  The "stable" version could be found [in the FreeBSD ports tree](https://cgit.freebsd.org/ports/log/net/wifibox-alpine/) and there is a "current" version [on GitHub](https://github.com/pgj/freebsd-wifibox-port).

You will also probably note that `net/wifibox-alpine` offers many other improvements other than the SquashFS-based layout.  It adds specific support for Broadcom and (802.11ac and 802.11ax) Realtek wireless devices and it is shipped with a slimmer, optimized version of Linux which requires much less memory and boots faster.  In addition to that, I am currently working on moving to Linux 6.1 and adding extra support for Linux 6.4.  This all has an impact on the range of supported hardware.

Please check this out and let me know if your hardware still needs work to be supported.  I am happy to help with making it work.  Just open a ticket or a discussion about that [at the Wifibox main repository](https://github.com/pgj/freebsd-wifibox/issues/new/choose).
